# Generated by Django 6.0.2 on 2026-02-18 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_label', models.CharField(blank=True, default='', max_length=120)),
                ('customer_label', models.CharField(blank=True, default='Guest', max_length=80)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('room_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('action_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('action_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(blank=True, limit_choices_to={'role': 'CONSULTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.location')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED'), ('consultant__isnull', False)), fields=('consultant', 'date', 'time'), name='uniq_consultant_timeslot_when_accepted'), models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED'), ('location__isnull', False), ('room_number__isnull', False)), fields=('location', 'date', 'time', 'room_number'), name='uniq_room_timeslot_when_accepted')],
            },
        ),
    ]
